name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:beta

    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Print Dart version
        run: dart --version
      - name: Install dependencies
        run: dart pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed lib test example
      - name: Analyzer
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Tests
        run: dart run test_coverage --no-badge --print-test-output --min-coverage 100
