name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed lib test example
      - name: Analyzer
        run: dartanalyzer --fatal-infos --fatal-warnings lib test example
      - name: Tests
        run: pub run test_coverage --no-badge --print-test-output --min-coverage 100
