name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Print Dart version
        run: dart --version
      - name: Install dependencies
        run: dart pub get
      - name: Formatter
        run: dart format --output none --set-exit-if-changed example lib test
      - name: Analyzer
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Tests
        run: dart test --coverage=coverage
      - name: Coverage
        run: dart run coverage:format_coverage -l -c -i coverage --report-on=lib --packages=.packages | dart run check_coverage:check_coverage
