# https://dart.dev/tools/pub/automated-publishing
name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'


# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: git config --global --add safe.directory '*' && git submodule update --init --recursive
      - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
