# https://dart.dev/tools/pub/automated-publishing
name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    needs: prepare
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
  prepare:
    uses: ./test.yml